"""add is_selected to job_candidates

Revision ID: 651f7d9b69b1
Revises: 63e12309e5a1
Create Date: 2026-05-07 09:24:38.048538+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651f7d9b69b1'
down_revision: Union[str, None] = '63e12309e5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('job_candidates', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_selected',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.create_index(
            batch_op.f('ix_job_candidates_is_selected'),
            ['is_selected'],
            unique=False,
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_candidates_is_selected'))
        batch_op.drop_column('is_selected')

    # ### end Alembic commands ###
